package controller.Admin;

import com.example.byod.model.Report;
import utils.DataStore;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;

public class ReportsController extends BaseAdminController {

    @FXML private TableView<Report> reportsTable;
    @FXML private TableColumn<Report, String> colReportID;
    @FXML private TableColumn<Report, String> colTitle;
    @FXML private TableColumn<Report, String> colGeneratedDate;
    @FXML private TableColumn<Report, String> colGeneratedBy;
    @FXML private TableColumn<Report, String> colActions;
    @FXML private TextField txtSearch;
    @FXML private Label statusEntriesLabel;

    @FXML
    public void initialize() {
        colReportID.setCellValueFactory(new PropertyValueFactory<>("reportId"));
        colTitle.setCellValueFactory(new PropertyValueFactory<>("title"));
        colGeneratedDate.setCellValueFactory(new PropertyValueFactory<>("generatedDate"));
        colGeneratedBy.setCellValueFactory(new PropertyValueFactory<>("generatedBy"));

        colActions.setCellFactory(param -> new TableCell<Report, String>() {
            private final Button btnView = new Button("View");
            private final Button btnPrint = new Button("Print");
            private final javafx.scene.layout.HBox pane = new javafx.scene.layout.HBox(10, btnView, btnPrint);

            {
                btnView.setStyle("-fx-background-color: #500A0E; -fx-text-fill: white; -fx-cursor: hand; -fx-padding: 5 10;");
                btnPrint.setStyle("-fx-background-color: #777777; -fx-text-fill: white; -fx-cursor: hand; -fx-padding: 5 10;");

                btnView.setOnAction(event -> {
                    Report report = getTableView().getItems().get(getIndex());

                    Alert viewAlert = new Alert(Alert.AlertType.INFORMATION);
                    viewAlert.setTitle("System Report Viewer");
                    viewAlert.setHeaderText("Document: " + report.getTitle());

                    TextArea textArea = new TextArea();
                    textArea.setEditable(false);
                    textArea.setWrapText(true);
                    textArea.setStyle("-fx-font-family: 'Consolas', monospace; -fx-font-size: 13px;");

                    String reportContent =
                            "==============================================================\n" +
                                    "                  BYOD SYSTEM AUDIT REPORT\n" +
                                    "==============================================================\n" +
                                    "REPORT ID    : " + report.getReportId() + "\n" +
                                    "DOCUMENT     : " + report.getTitle() + "\n" +
                                    "GENERATED BY : " + report.getGeneratedBy() + "\n" +
                                    "TIMESTAMP    : " + report.getGeneratedDate() + "\n" +
                                    "--------------------------------------------------------------\n" +
                                    "EXECUTIVE SUMMARY:\n" +
                                    "This system-generated report encapsulates the hardware \n" +
                                    "handshake logs and access metrics for the specified period.\n\n" +
                                    "KEY METRICS:\n" +
                                    "- Total Gateway Scans         : 1,425\n" +
                                    "- Authenticated Check-ins     : 1,382\n" +
                                    "- Unregistered Assets Flagged : 43\n" +
                                    "- High-Risk Security Events   : 2\n\n" +
                                    "RECENT ANOMALY LOG (SAMPLE):\n" +
                                    "[08:14:22] MAC: 00:1B:44:11:3A:B7 (Main Gate) - VERIFIED\n" +
                                    "[09:22:11] MAC: F4:09:D8:01:A2:CC (South Gate) - DENIED\n" +
                                    "[11:05:49] MAC: 1A:2B:3C:4D:5E:6F (Main Gate) - DENIED\n\n" +
                                    "*** END OF SECURE REPORT ***";

                    textArea.setText(reportContent);
                    textArea.setPrefWidth(550);
                    textArea.setPrefHeight(350);

                    viewAlert.getDialogPane().setContent(textArea);
                    viewAlert.showAndWait();
                });

                btnPrint.setOnAction(event -> {
                    Report report = getTableView().getItems().get(getIndex());

                    Alert printConfirm = new Alert(Alert.AlertType.CONFIRMATION);
                    printConfirm.setTitle("Print Manager");
                    printConfirm.setHeaderText("Print Confirmation");
                    printConfirm.setContentText("Are you sure you want to send '" + report.getTitle() + "' to the local printer?");

                    printConfirm.showAndWait().ifPresent(response -> {
                        if (response == ButtonType.OK) {
                            Alert success = new Alert(Alert.AlertType.INFORMATION);
                            success.setTitle("Printer Status");
                            success.setHeaderText(null);
                            success.setContentText("Successfully routed to the printer queue.");
                            success.showAndWait();
                        }
                    });
                });
            }

            @Override
            protected void updateItem(String item, boolean empty) {
                super.updateItem(item, empty);
                setGraphic(empty ? null : pane);
            }
        });

        reportsTable.setItems(DataStore.getInstance().getReportsList());

        Label placeholder = new Label("No records available.");
        placeholder.setStyle("-fx-text-fill: #888888; -fx-font-style: italic; -fx-font-size: 13px;");
        reportsTable.setPlaceholder(placeholder);

        int count = DataStore.getInstance().getReportsList().size();
        statusEntriesLabel.setText("Showing 1 to " + count + " of " + count + " entries");
    }
}